// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juahafdtttezrwyinbkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1YWhhZmR0dHRlenJ3eWluYmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzA5NjksImV4cCI6MjA1OTk0Njk2OX0.bo53ijbNFLGobJ-LtPNjVFV5fBHiTCIgyX1HV2INoCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);